### ISSUE TITLE
Does not point North on the iPhone

### ISSUE THREAD

**Issue by stuartlangridge** [WebUtils/Compass#1]
As far as I can tell, the app decides that "North" is "towards the top of the iphone when the app starts", rather than "towards actual North".

**Comment by chrisalexander** [comment]
Aha, looks like iOS has an offset from initial reading rather than the absolute value: https://developer.apple.com/library/safari/documentation/SafariDOMAdditions/Reference/DeviceOrientationEventClassRef/DeviceOrientationEvent/DeviceOrientationEvent.html#//apple_ref/javascript/instp/DeviceOrientationEvent/webkitCompassHeading

**Comment by chrisalexander** [comment]
Took two attempts, and it's not an awesome fix (TBH the API for some reason sucks, which is my excuse) but it at least points the right direction on iOS now...

**Comment by mahemoff** [comment]
Cool, I'm getting same results on iPhone as the built-in app :).
